apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
data:
  JWT_SECRET: ZGV2b3BzX2p3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA=  # devops_jwt_secret_key_1234567890 (base64 encoded)
