apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-app
data:
  # Backend Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "devops_app"
  DB_USER: "devops_user"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  NODE_ENV: "production"
  PORT: "5000"
  
  # Frontend Configuration
  REACT_APP_API_URL: "/api"
  REACT_APP_FRONTEND_URL: "http://localhost:3000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: devops-app
data:
  POSTGRES_DB: "devops_app"
  POSTGRES_USER: "devops_user"
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devops-app
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream backend {
            server backend-service:5000;
        }
        
        upstream frontend {
            server frontend-service:3000;
        }
        
        server {
            listen 80;
            server_name localhost;
            
            location /api/ {
                proxy_pass http://backend/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location / {
                proxy_pass http://frontend/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
