apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - statefulset.yaml
  - deployments.yaml
  - services.yaml
  - ingress.yaml




