apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
data:
  # Base64 encoded secrets (change these in production!)
  DB_PASSWORD: ZGV2b3BzX3Bhc3N3b3Jk  # devops_password
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-super-secret-key-change-in-production

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-app
type: Opaque
data:
  POSTGRES_PASSWORD: ZGV2b3BzX3Bhc3N3b3Jk  # devops_password
