apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
data:
  MONGODB_USERNAME: ZGV2b3BzX3VzZXI=  
  MONGODB_PASSWORD: ZGV2b3BzX3Bhc3N3b3Jk 
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devops-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: ZGV2b3BzX3VzZXI= 
  MONGO_INITDB_ROOT_PASSWORD: ZGV2b3BzX3Bhc3N3b3Jk  
  MONGO_INITDB_DATABASE: ZGV2b3BzX2FwcA== 