apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n "your-value" | base64
  MONGODB_USERNAME: ZGV2b3BzX3VzZXI=  # devops_user
  MONGODB_PASSWORD: ZGV2b3BzX3Bhc3N3b3Jk  # devops_password
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # your-super-secret-jwt-key-change-this-in-production

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devops-app
type: Opaque
data:
  # MongoDB root credentials
  MONGO_INITDB_ROOT_USERNAME: ZGV2b3BzX3VzZXI=  # devops_user
  MONGO_INITDB_ROOT_PASSWORD: ZGV2b3BzX3Bhc3N3b3Jk  # devops_password
  MONGO_INITDB_DATABASE: ZGV2b3BzX2FwcA==  # devops_app