name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: zivanovskas/devops-project


jobs:
  # CI Job - Build and Test
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false
      continue-on-error: true

    - name: Run backend tests
      working-directory: ./backend
      run: npm test
      continue-on-error: true

    - name: Build frontend
      working-directory: ./frontend
      run: CI=false npm run build

  # CD Job - Build and Push Docker Images
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}-backend
          org.opencontainers.image.description=Backend API for DevOps Project
          org.opencontainers.image.version=${{ github.sha }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}-frontend
          org.opencontainers.image.description=Frontend for DevOps Project
          org.opencontainers.image.version=${{ github.sha }}

    - name: Build and push nginx image
      uses: docker/build-push-action@v5
      with:
        context: ./nginx
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx:${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}-nginx
          org.opencontainers.image.description=Nginx for DevOps Project
          org.opencontainers.image.version=${{ github.sha }}

  # Optional: Deploy to AWS EC2 (Bonus Points)
  deploy:
    needs: cd
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/devops-project
          git pull origin main
          docker-compose pull
          docker-compose up -d
          echo "Deployment completed successfully!"